// app/layout.js

import { Outfit } from "next/font/google";
import "./globals.css";
import ClientProviders from "./_components/ClientProviders"; // ✅

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Naught AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className} suppressHydrationWarning>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
